stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
  script:
    - echo "Настройка SSH для подключения"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
    - echo "Деплой на VPS"
    - ssh -v -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << "EOF"
        cd ~/backend
        docker compose stop
        git fetch
        git pull
        docker compose up --build -d
      EOF
  only:
    - master