stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  
  script:
    # Создаём директорию /backend на сервере, если она ещё не создана
    - ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "sudo mkdir -p /backend"
    # Копируем файлы в директорию /backend на сервере
    - scp -r -o StrictHostKeyChecking=no . ${SSH_USER}@${SSH_HOST}:/backend
    # Заходим на сервер и выполняем команды деплоя
    - ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
        sudo cd /backend &&
        sudo docker-compose down &&
        sudo docker-compose up --build -d
      "
  only:
    - master
