# Определяем стадии сборки и деплоя
stages:
  - deploy


# Деплой Docker-образа на удаленный VPS через SSH
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client # Устанавливаем openssh-client для работы с SSH
  script:
    - echo "Настройка SSH для подключения"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Записываем приватный ключ в файл
    - chmod 600 ~/.ssh/id_rsa  # Устанавливаем права доступа к приватному ключу
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts  # Добавляем хост в список известных
    - echo "Деплой на VPS"
    - echo "Скоро..."
  only:
    - master  # Деплой тоже происходит только с главной ветки

# Переменные для подключения к VPS
# SSH_HOST, SSH_USER, SSH_PRIVATE_KEY следует задать в GitLab CI/CD Settings как Secret variables
